name: Refresh Docs

on:
  workflow_dispatch
        
env:
  BRANCH_NAME: docs-refresh

jobs:
  apply-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set Name
        run: git config --global user.name "GitHub"
      - name: Set Email
        run: git config --global user.email "noreply@github.com"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run refresh-docs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: Documentation Refresh
          body: Refreshed the documentation to the latest version.
          assignees: kgar
          reviewers: kgar
